services:
  - type: web
    name: dartconnect-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: gunicorn app:app
    plan: free